# Generated by Django 5.2.18 on 2026-10-07 19:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sku", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("piece", "Piece"),
                            ("set", "Set"),
                            ("meter", "Meter"),
                            ("ml", "Milliliter"),
                            ("gram", "Gram"),
                        ],
                        default="piece",
                        max_length=10,
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "selling_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "low_stock_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "quantity_on_hand",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "quantity_reserved",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PartReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Reserved"),
                            ("consumed", "Consumed"),
                            ("released", "Released"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=80)),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="orders.repairorder",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="inventory.part",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("receipt", "Stock received"),
                            ("adjustment", "Manual adjustment"),
                            ("reservation", "Reserved for order"),
                            ("release", "Reservation released"),
                            ("consumption", "Used in repair"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "on_hand_delta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "reserved_delta",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("on_hand_after", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "reserved_after",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("idempotency_key", models.CharField(blank=True, max_length=80)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.repairorder",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventory.part",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.partreservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.UniqueConstraint(
                fields=("business", "sku"), name="part_sku_unique_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_on_hand__gte", 0)),
                name="part_on_hand_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity_reserved__gte", 0)),
                name="part_reserved_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("quantity_reserved__lte", models.F("quantity_on_hand"))
                ),
                name="part_reserved_within_on_hand",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purchase_cost__gte", 0), ("selling_price__gte", 0)
                ),
                name="part_prices_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.CheckConstraint(
                condition=models.Q(("low_stock_threshold__gte", 0)),
                name="part_threshold_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="partreservation",
            constraint=models.UniqueConstraint(
                fields=("business", "idempotency_key"),
                name="reservation_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="partreservation",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="reservation_quantity_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["business", "part", "-created_at"],
                name="inventory_s_busines_087e69_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("business", "idempotency_key"),
                name="movement_idempotency_unique",
            ),
        ),
    ]
