# Generated by Django 5.2.18 on 2026-10-07 19:45

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estimate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to customer"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("superseded", "Superseded"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Shown to the customer."),
                ),
                ("currency", models.CharField(max_length=3)),
                ("tax_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "tax_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decided_by_name", models.CharField(blank=True, max_length=200)),
                (
                    "decision_channel",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("portal", "Customer portal"),
                            ("link", "Approval link"),
                            ("staff", "Recorded by staff on the customer's behalf"),
                        ],
                        max_length=10,
                    ),
                ),
                ("decision_note", models.TextField(blank=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estimates",
                        to="orders.repairorder",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-version"],
            },
        ),
        migrations.CreateModel(
            name="ApprovalLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approval_links",
                        to="estimates.estimate",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EstimateLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("labor", "Labor"), ("part", "Part"), ("fee", "Fee")],
                        max_length=10,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=64)),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("taxable", models.BooleanField(default=True)),
                ("line_total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "estimate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="estimates.estimate",
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="inventory.part",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.UniqueConstraint(
                fields=("order", "version"), name="estimate_unique_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["draft", "sent"])),
                fields=("order",),
                name="estimate_one_open_version_per_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "total",
                        django.db.models.expressions.CombinedExpression(
                            models.F("subtotal"), "+", models.F("tax_total")
                        ),
                    )
                ),
                name="estimate_total_consistent",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ["approved", "rejected"]), _negated=True),
                    ("decided_at__isnull", False),
                    _connector="OR",
                ),
                name="estimate_decision_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimateline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="estimate_line_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="estimateline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)),
                name="estimate_line_price_non_negative",
            ),
        ),
    ]
