# Generated by Django 5.2.18 on 2026-10-07 19:45

import apps.orders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("businesses", "0001_initial"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepairOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.PositiveIntegerField()),
                ("problem_description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("scheduled", "Scheduled"),
                            ("diagnosing", "Diagnosing"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("in_progress", "In progress"),
                            ("ready_for_pickup", "Ready for pickup"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=24,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("not_invoiced", "Not invoiced"),
                            ("unpaid", "Unpaid"),
                            ("partially_paid", "Partially paid"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="not_invoiced",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("staff", "Created by staff"),
                            ("portal", "Customer request"),
                        ],
                        default="staff",
                        max_length=10,
                    ),
                ),
                ("expected_completion_date", models.DateField(blank=True, null=True)),
                ("diagnostic_findings", models.TextField(blank=True)),
                ("diagnosed_at", models.DateTimeField(blank=True, null=True)),
                ("status_changed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "assigned_technician",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.customer",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="customers.device",
                    ),
                ),
                (
                    "diagnosed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Order created"),
                            ("status_changed", "Status changed"),
                            ("assigned", "Technician assigned"),
                            ("updated", "Details updated"),
                            ("diagnostics", "Diagnostics recorded"),
                            ("internal_note", "Internal note"),
                            ("customer_update", "Customer update"),
                            ("attachment", "Attachment added"),
                            ("estimate", "Estimate"),
                            ("parts", "Parts"),
                            ("appointment", "Appointment"),
                            ("invoice", "Invoice"),
                            ("payment", "Payment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=200)),
                ("message", models.TextField(blank=True)),
                ("visible_to_customer", models.BooleanField(default=False)),
                ("from_status", models.CharField(blank=True, max_length=24)),
                ("to_status", models.CharField(blank=True, max_length=24)),
                ("data", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orders.repairorder",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "public_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=255, upload_to=apps.orders.models.attachment_path
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("sha256", models.CharField(max_length=64)),
                ("visible_to_customer", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="businesses.business",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="orders.repairorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(
                fields=["business", "status"], name="orders_repa_busines_6d72be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(
                fields=["business", "assigned_technician", "status"],
                name="orders_repa_busines_853895_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="repairorder",
            index=models.Index(
                fields=["business", "-created_at"],
                name="orders_repa_busines_c435af_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="repairorder",
            constraint=models.UniqueConstraint(
                fields=("business", "number"), name="order_number_unique_per_business"
            ),
        ),
        migrations.AddConstraint(
            model_name="repairorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "completed"), _negated=True),
                    ("completed_at__isnull", False),
                    _connector="OR",
                ),
                name="order_completed_has_timestamp",
            ),
        ),
        migrations.AddConstraint(
            model_name="repairorder",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "cancelled"), _negated=True),
                    ("cancelled_at__isnull", False),
                    _connector="OR",
                ),
                name="order_cancelled_has_timestamp",
            ),
        ),
        migrations.AddIndex(
            model_name="orderevent",
            index=models.Index(
                fields=["order", "created_at"], name="orders_orde_order_i_4c5f76_idx"
            ),
        ),
    ]
