# Generated by Django 5.2.18 on 2026-10-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="last_event_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
